details: "darker"
accent: "#fff300"
foreground: "#ffffff"
background: "#031c29"
background_image:
  path: ~/wallpapers/milky_mountain.jpg
  opacity: 40
terminal_colors:
  bright:
    black: "#5c5c61"
    red: "#f5b2ac"
    yellow: "#fad000"
    cyan: "#80fcff"
    green: "#00ff7f"
    blue: "#6943ff"
    white: "#ffffff"
    magenta: "#ffa8fe"
  normal:
    black: "#000000"
    green: "#00ff7f"
    blue: "#7857fe"
    red: "#f5b2ac"
    yellow: "#fad000"
    cyan: "#80fcff"
    magenta: "#ffa8fe"
    white: "#ffffff"
