live_config_reload = true

[env]
TERM = "xterm-256color"

[font]
size = 12

[font.glyph_offset]
x = 0
y = 0

[font.normal]
family = "MesloLGS NF"

[font.offset]
x = 0
y = 0

[shell]
program = "/opt/homebrew/bin/zsh"
args = [
    "-l",
    "-c",
    "cd ~/ && (/opt/homebrew/bin/tmux a -t 0 || /opt/homebrew/bin/tmux -u)",
]

[window]
opacity = 0.8
