format = """\
[ $os in container ](bg:#6696ff fg:#090c0c)\
[](fg:#6696ff bg:#FFFFFF)\
$username\
[](fg:#FFFFFF bg:#3B76F0)\
$directory\
[](fg:#3B76F0 bg:#00507A)\
$python\
[](fg:#00507A bg:#8fff96)\
$git_branch\
$git_status\
$git_metrics\
[](fg:#8fff96 bg:#1C3A5E)\
$cmd_duration\
[](fg:#1c3a5e)\
$line_break\
$character\
"""

[os]
disabled = false
format = "$symbol"

[os.symbols]
Arch = ""
Macos = ""
Ubuntu = ""
Windows = "󰍲"
Debian = ""
Raspbian = ""

[hostname]
format = "[ $ssh_symbol$hostname ]($style)"
style = "fg:#1C3A5E bg:#adc7ff"
disabled=false
ssh_only=false

[username]
format = "[ $user ]($style)"
style_user = "fg:#1C3A5E bg:#ffffff"
style_root = "fg:#1C3A5E bg:#ffffff"
show_always = true

[directory]
format = "[ $path ]($style)"
style = "fg:#E4E4E4 bg:#3B76F0"
truncation_length = 15
truncate_to_repo = false

[python]
format = '[ py:${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
style = "fg:#E4E4E4 bg:#00507A"

[git_branch]
format = '[ $symbol$branch(:$remote_branch) ]($style)'
symbol = "  "
style = "fg:#1C3A5E bg:#8fff96"

[git_status]
format = '[$all_status]($style)'
style = "fg:#1C3A5E bg:#8fff96"

[git_metrics]
format = "([+$added]($added_style))[ ]($added_style)"
added_style = "fg:#1C3A5E bg:#8fff96"
deleted_style = "fg:bright-red bg:235"
disabled = false

[hg_branch]
format = "[ $symbol$branch ]($style)"
symbol = " "

[character]
format = '$symbol'
success_symbol = '[ ❯ ](green)'
error_symbol = '[ ❯ ](green)'
vimcmd_symbol = '[ ❯ ](#ADC7FF)'

[cmd_duration]
format = '[ $duration ]($style)'
style = "fg:#8dfbd2 bg:#1c3a5e"
show_milliseconds = true
min_time = 0

[time]
disabled = true
time_format = "%T" # H:M:S
style = "bg:#1d2230"
format = '[[ 󱑍 $time ](bg:#1C3A5E fg:#8DFBD2)]($style)'
